<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <UseAppHost>false</UseAppHost>
    <RootNamespace>SecondEcran</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="../../Core/*.cs" />
    <EmbeddedResource Include="../../Web/index.html" LogicalName="index.html" />
  </ItemGroup>
</Project>
